CREATE TABLE customer
(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name text NOT NULL,
    phone text NOT NULL,
    spent numeric(18, 2) NOT NULL DEFAULT 0,

    version bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);