CREATE TABLE customer_spent_history
(
    id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ,
    customer_id     BIGINT REFERENCES customer (id) NOT NULL,
    amount          numeric(18, 2)                  NOT NULL,
    spend_timestamp timestamp without time zone     NOT NULL,

    version         bigint                          NOT NULL DEFAULT 0,
    created_at      timestamp without time zone     NOT NULL,
    updated_at      timestamp without time zone     NOT NULL
);