server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://[::1]:5432/${spring.application.name}
    username: application
    password: postgres
  flyway:
    url: jdbc:postgresql://[::1]:5432/${spring.application.name}
    default-schema: application
    user: application
    password: postgres
    loggers: log4j2
  jpa:
    show-sql: true
